name: Bug Report
description: Report a bug or issue with PrismQ.IdeaCollector
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Configure settings '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: source
    attributes:
      label: Source Plugin
      description: Which source plugin is affected (if applicable)?
      options:
        - YouTube
        - Reddit
        - N/A - Core functionality
        - Multiple sources
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g., Windows 10, Ubuntu 22.04]
        - Python Version: [e.g., 3.10.5]
        - PrismQ.IdeaCollector Version: [e.g., 1.0.0]
      value: |
        - OS: 
        - Python Version: 
        - PrismQ.IdeaCollector Version: 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any relevant error messages or logs
      placeholder: Paste error logs here
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Any additional information that might help
    validations:
      required: false
